import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { DemoToggle } from "@/components/DemoToggle";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} font-sans h-full antialiased`}
    >
      <body className={`${poppins.className} ${poppins.variable} antialiased bg-slate-50 text-slate-900 selection:bg-primary/20`}>
        {children}
        <DemoToggle />
        <Toaster />
      </body>
    </html>
  );
}
